language: ruby
branches:
  only:
    - master
matrix:
  include:
    # See https://docs.travis-ci.com/user/reference/osx/
    - os: osx
      osx_image: xcode11
      # macOS 10.14
    - os: osx
      osx_image: xcode10
      # macOS 10.13
install:
  - brew update
  - brew cask install xquartz
  - brew install jpeg-turbo makeicns
script:
  - make
  - make install
  - open /Applications/AzPainter.app
  - sleep 10
  - pgrep azpainter
  - pkill azpainter
